### ISSUE TITLE
Testing Github Flow

### ISSUE THREAD

**Issue by zackarno** [impact-initiatives-geospatial/easyrgee#4]
We are trying a couple new work flows out: 
1. Github flow instead of gitflow 
2. Github projects

I want to do some testing to see how this could work out. @mhkhan27 - lets try something simple

**Task:** update the readme to include links to `rgee` and `exploreRGEE` packages
**Steps**  *(i also want to try out these check-boxes)*:
- [x] clone repo ( I have given you write access)
- [x] create feature branch to update readme - call it something descriptive
- [x] make changes and commit
- [x] make sure your local master branch is in sync with remote master -fetch/pull
- [x] push feature branch to remote
- [x] submit a pull request asking me to merge to master (do not approve pull request yourself)

**Comment by zackarno** [comment]
nice - `GitHub Projects` is automation seems to be working well. Going to close this.
